export const StreamlitProjects = [
  {
    repo: "gowth-mindset-streamlit",
    branch: "main",
    path: "challenge.py",
    link: "https://share.streamlit.io/areebayaseen15/gowth-mindset-streamlit/main/challenge.py",
    github: "https://github.com/areebayaseen15/gowth-mindset-streamlit",
  },
  {
    repo: "Data Sweeper app",
    branch: "main",
    path: "app.py",
    link: "https://grotwth-mindset-challenge-q3-9qycxen3uippswraleqnft.streamlit.app/",
    github: "https://github.com/areebayaseen15/grotwth-mindset-challenge-q3/blob/main/app.py",
  },

  {
    repo: "password-strength-meter-streamlit",
    branch: "main",
    path: "main.py",
    link: "https://share.streamlit.io/areebayaseen15/password-strength-meter-streamlit/main/main.py",
    github: "https://github.com/areebayaseen15/password-strength-meter-streamlit/blob/main/main.py",
  },
  {
    repo: "python-assignment-05",
    branch: "main",
    path: "secure_data.py",
    link: "https://share.streamlit.io/areebayaseen15/python-assignment-05/main/secure_data.py",
    github: "https://github.com/areebayaseen15/python-assignment-05/blob/main/secure_data.py",
  },
  {
    repo: "python-unit-convertor",
    branch: "main",
    path: "main.py",
    link: "https://share.streamlit.io/areebayaseen15/python-unit-convertor/main/main.py",
    github: "https://github.com/areebayaseen15/python-unit-convertor/blob/main/main.py",
  },
  {
    repo: "quarter_4_agentic_ai-with-sir-aneeq",
    branch: "main",
    path: "task1/Practical Work/Repo_03_Open_Roter/app.py",
    link: "https://share.streamlit.io/areebayaseen15/quarter_4_agentic_ai-with-sir-aneeq/main/task1/Practical Work/Repo_03_Open_Roter/app.py",
    github: "https://github.com/areebayaseen15/quarter_4_agentic_ai-with-sir-aneeq",
  },
  {
    repo: "ramadan-coding-nights-python",
    branch: "main",
    path: "coding-night-10-simple-calculator/simple-calculator/main.py",
    link: "https://share.streamlit.io/areebayaseen15/ramadan-coding-nights-python/main/coding-night-10-simple-calculator/simple-calculator/main.py",
    github: "https://github.com/areebayaseen15/ramadan-coding-nights-python/blob/main/coding-night-10-simple-calculator/simple-calculator/main.py",
  },
  {
    repo: "ramadan-coding-nights-python",
    branch: "main",
    path: "coding-night-12-joke-generator/main.py",
    link: "https://share.streamlit.io/areebayaseen15/ramadan-coding-nights-python/main/coding-night-12-joke-generator/main.py",
    github: "https://github.com/areebayaseen15/ramadan-coding-nights-python/blob/main/coding-night-12-joke-generator/main.py",
  },
  {
    repo: "ramadan-coding-nights-python",
    branch: "main",
    path: "coding-night-6-Time-Zone/time-zone/main.py",
    link: "https://share.streamlit.io/areebayaseen15/ramadan-coding-nights-python/main/coding-night-6-Time-Zone/time-zone/main.py",
    github: "https://github.com/areebayaseen15/ramadan-coding-nights-python/blob/main/coding-night-6-Time-Zone/time-zone/main.py",
  },
  {
    repo: "ramadan-coding-nights-python",
    branch: "main",
    path: "coding-night-8-Quiz-app/quiz-app/main.py",
    link: "https://share.streamlit.io/areebayaseen15/ramadan-coding-nights-python/main/coding-night-8-Quiz-app/quiz-app/main.py",
    github: "https://github.com/areebayaseen15/ramadan-coding-nights-python/blob/main/coding-night-8-Quiz-app/quiz-app/main.py",
  },
  {
    repo: "ramadan-coding-nights-python",
    branch: "main",
    path: "coding-night7-Mood-tracker/mood-tracker/main.py",
    link: "https://share.streamlit.io/areebayaseen15/ramadan-coding-nights-python/main/coding-night7-Mood-tracker/mood-tracker/main.py",
    github: "https://github.com/areebayaseen15/ramadan-coding-nights-python/blob/main/coding-night7-Mood-tracker/mood-tracker/main.py",
  },
  {
    repo: "ramadan-coding-nights-python",
    branch: "main",
    path: "codingNight-5_Money_making_machine/money_making_machine/money-making-machine.py",
    link: "https://share.streamlit.io/areebayaseen15/ramadan-coding-nights-python/main/codingNight-5_Money_making_machine/money_making_machine/money-making-machine.py",
    github: "https://github.com/areebayaseen15/ramadan-coding-nights-python/blob/main/codingNight-5_Money_making_machine/money_making_machine/money-making-machine.py",
  },
  {
    repo: "ramadan-coding-nights-python",
    branch: "main",
    path: "PhoneNumberDetails/main.py",
    link: "https://share.streamlit.io/areebayaseen15/ramadan-coding-nights-python/main/PhoneNumberDetails/main.py",
    github: "https://github.com/areebayaseen15/ramadan-coding-nights-python/blob/main/PhoneNumberDetails/main.py",
  },
];
